/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.records;


import cn.personal.jooq.model.jooq.tables.DemoInfo;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DemoInfoRecord extends UpdatableRecordImpl<DemoInfoRecord> implements
    Record3<Long, String, String> {

  private static final long serialVersionUID = -1159443233;

  /**
   * Setter for <code>mydata.demo_info.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>mydata.demo_info.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>mydata.demo_info.password</code>.
   */
  public void setPassword(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>mydata.demo_info.password</code>.
   */
  public String getPassword() {
    return (String) get(1);
  }

  /**
   * Setter for <code>mydata.demo_info.username</code>.
   */
  public void setUsername(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>mydata.demo_info.username</code>.
   */
  public String getUsername() {
    return (String) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row3<Long, String, String> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row3<Long, String, String> valuesRow() {
    return (Row3) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field1() {
    return DemoInfo.DEMO_INFO.ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field2() {
    return DemoInfo.DEMO_INFO.PASSWORD;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return DemoInfo.DEMO_INFO.USERNAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component2() {
    return getPassword();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getUsername();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value2() {
    return getPassword();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getUsername();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public DemoInfoRecord value1(Long value) {
    setId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public DemoInfoRecord value2(String value) {
    setPassword(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public DemoInfoRecord value3(String value) {
    setUsername(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public DemoInfoRecord values(Long value1, String value2, String value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached DemoInfoRecord
   */
  public DemoInfoRecord() {
    super(DemoInfo.DEMO_INFO);
  }

  /**
   * Create a detached, initialised DemoInfoRecord
   */
  public DemoInfoRecord(Long id, String password, String username) {
    super(DemoInfo.DEMO_INFO);

    set(0, id);
    set(1, password);
    set(2, username);
  }
}
