/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.records;


import cn.personal.jooq.model.jooq.tables.LgUserAmount;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户资产表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LgUserAmountRecord extends UpdatableRecordImpl<LgUserAmountRecord> implements
    Record9<Long, Long, BigDecimal, String, LocalDateTime, Long, LocalDateTime, Long, String> {

  private static final long serialVersionUID = 543936140;

  /**
   * Setter for <code>mydata.lg_user_amount.id</code>. 主键
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>mydata.lg_user_amount.id</code>. 主键
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>mydata.lg_user_amount.company_user_id</code>. 用户ID
   */
  public void setCompanyUserId(Long value) {
    set(1, value);
  }

  /**
   * Getter for <code>mydata.lg_user_amount.company_user_id</code>. 用户ID
   */
  public Long getCompanyUserId() {
    return (Long) get(1);
  }

  /**
   * Setter for <code>mydata.lg_user_amount.amount</code>. 资产
   */
  public void setAmount(BigDecimal value) {
    set(2, value);
  }

  /**
   * Getter for <code>mydata.lg_user_amount.amount</code>. 资产
   */
  public BigDecimal getAmount() {
    return (BigDecimal) get(2);
  }

  /**
   * Setter for <code>mydata.lg_user_amount.amount_type</code>. 资产类型
   */
  public void setAmountType(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>mydata.lg_user_amount.amount_type</code>. 资产类型
   */
  public String getAmountType() {
    return (String) get(3);
  }

  /**
   * Setter for <code>mydata.lg_user_amount.create_time</code>. 新增日期
   */
  public void setCreateTime(LocalDateTime value) {
    set(4, value);
  }

  /**
   * Getter for <code>mydata.lg_user_amount.create_time</code>. 新增日期
   */
  public LocalDateTime getCreateTime() {
    return (LocalDateTime) get(4);
  }

  /**
   * Setter for <code>mydata.lg_user_amount.create_id</code>. 新增人ID
   */
  public void setCreateId(Long value) {
    set(5, value);
  }

  /**
   * Getter for <code>mydata.lg_user_amount.create_id</code>. 新增人ID
   */
  public Long getCreateId() {
    return (Long) get(5);
  }

  /**
   * Setter for <code>mydata.lg_user_amount.update_time</code>. 修改日期
   */
  public void setUpdateTime(LocalDateTime value) {
    set(6, value);
  }

  /**
   * Getter for <code>mydata.lg_user_amount.update_time</code>. 修改日期
   */
  public LocalDateTime getUpdateTime() {
    return (LocalDateTime) get(6);
  }

  /**
   * Setter for <code>mydata.lg_user_amount.update_id</code>. 修改人ID
   */
  public void setUpdateId(Long value) {
    set(7, value);
  }

  /**
   * Getter for <code>mydata.lg_user_amount.update_id</code>. 修改人ID
   */
  public Long getUpdateId() {
    return (Long) get(7);
  }

  /**
   * Setter for <code>mydata.lg_user_amount.delete_flag</code>. 删除标记
   */
  public void setDeleteFlag(String value) {
    set(8, value);
  }

  /**
   * Getter for <code>mydata.lg_user_amount.delete_flag</code>. 删除标记
   */
  public String getDeleteFlag() {
    return (String) get(8);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record9 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row9<Long, Long, BigDecimal, String, LocalDateTime, Long, LocalDateTime, Long, String> fieldsRow() {
    return (Row9) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row9<Long, Long, BigDecimal, String, LocalDateTime, Long, LocalDateTime, Long, String> valuesRow() {
    return (Row9) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field1() {
    return LgUserAmount.LG_USER_AMOUNT.ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field2() {
    return LgUserAmount.LG_USER_AMOUNT.COMPANY_USER_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<BigDecimal> field3() {
    return LgUserAmount.LG_USER_AMOUNT.AMOUNT;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field4() {
    return LgUserAmount.LG_USER_AMOUNT.AMOUNT_TYPE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field5() {
    return LgUserAmount.LG_USER_AMOUNT.CREATE_TIME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field6() {
    return LgUserAmount.LG_USER_AMOUNT.CREATE_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field7() {
    return LgUserAmount.LG_USER_AMOUNT.UPDATE_TIME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field8() {
    return LgUserAmount.LG_USER_AMOUNT.UPDATE_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field9() {
    return LgUserAmount.LG_USER_AMOUNT.DELETE_FLAG;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component2() {
    return getCompanyUserId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public BigDecimal component3() {
    return getAmount();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component4() {
    return getAmountType();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component5() {
    return getCreateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component6() {
    return getCreateId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component7() {
    return getUpdateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component8() {
    return getUpdateId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component9() {
    return getDeleteFlag();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value2() {
    return getCompanyUserId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public BigDecimal value3() {
    return getAmount();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value4() {
    return getAmountType();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value5() {
    return getCreateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value6() {
    return getCreateId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value7() {
    return getUpdateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value8() {
    return getUpdateId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value9() {
    return getDeleteFlag();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord value1(Long value) {
    setId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord value2(Long value) {
    setCompanyUserId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord value3(BigDecimal value) {
    setAmount(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord value4(String value) {
    setAmountType(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord value5(LocalDateTime value) {
    setCreateTime(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord value6(Long value) {
    setCreateId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord value7(LocalDateTime value) {
    setUpdateTime(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord value8(Long value) {
    setUpdateId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord value9(String value) {
    setDeleteFlag(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LgUserAmountRecord values(Long value1, Long value2, BigDecimal value3, String value4,
      LocalDateTime value5, Long value6, LocalDateTime value7, Long value8, String value9) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached LgUserAmountRecord
   */
  public LgUserAmountRecord() {
    super(LgUserAmount.LG_USER_AMOUNT);
  }

  /**
   * Create a detached, initialised LgUserAmountRecord
   */
  public LgUserAmountRecord(Long id, Long companyUserId, BigDecimal amount, String amountType,
      LocalDateTime createTime, Long createId, LocalDateTime updateTime, Long updateId,
      String deleteFlag) {
    super(LgUserAmount.LG_USER_AMOUNT);

    set(0, id);
    set(1, companyUserId);
    set(2, amount);
    set(3, amountType);
    set(4, createTime);
    set(5, createId);
    set(6, updateTime);
    set(7, updateId);
    set(8, deleteFlag);
  }
}
