/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.records;


import cn.personal.jooq.model.jooq.tables.ModuleRole;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ModuleRoleRecord extends TableRecordImpl<ModuleRoleRecord> implements
    Record2<Integer, Integer> {

  private static final long serialVersionUID = 1015502437;

  /**
   * Setter for <code>mydata.module_role.rid</code>.
   */
  public void setRid(Integer value) {
    set(0, value);
  }

  /**
   * Getter for <code>mydata.module_role.rid</code>.
   */
  public Integer getRid() {
    return (Integer) get(0);
  }

  /**
   * Setter for <code>mydata.module_role.mid</code>.
   */
  public void setMid(Integer value) {
    set(1, value);
  }

  /**
   * Getter for <code>mydata.module_role.mid</code>.
   */
  public Integer getMid() {
    return (Integer) get(1);
  }

  // -------------------------------------------------------------------------
  // Record2 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row2<Integer, Integer> fieldsRow() {
    return (Row2) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row2<Integer, Integer> valuesRow() {
    return (Row2) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field1() {
    return ModuleRole.MODULE_ROLE.RID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field2() {
    return ModuleRole.MODULE_ROLE.MID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component1() {
    return getRid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component2() {
    return getMid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value1() {
    return getRid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value2() {
    return getMid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRoleRecord value1(Integer value) {
    setRid(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRoleRecord value2(Integer value) {
    setMid(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRoleRecord values(Integer value1, Integer value2) {
    value1(value1);
    value2(value2);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached ModuleRoleRecord
   */
  public ModuleRoleRecord() {
    super(ModuleRole.MODULE_ROLE);
  }

  /**
   * Create a detached, initialised ModuleRoleRecord
   */
  public ModuleRoleRecord(Integer rid, Integer mid) {
    super(ModuleRole.MODULE_ROLE);

    set(0, rid);
    set(1, mid);
  }
}
