/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.records;


import cn.personal.jooq.model.jooq.tables.Module;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ModuleRecord extends UpdatableRecordImpl<ModuleRecord> implements
    Record8<Integer, Integer, String, String, String, String, String, Short> {

  private static final long serialVersionUID = 406432079;

  /**
   * Setter for <code>mydata.module.mid</code>.
   */
  public void setMid(Integer value) {
    set(0, value);
  }

  /**
   * Getter for <code>mydata.module.mid</code>.
   */
  public Integer getMid() {
    return (Integer) get(0);
  }

  /**
   * Setter for <code>mydata.module.parent_id</code>.
   */
  public void setParentId(Integer value) {
    set(1, value);
  }

  /**
   * Getter for <code>mydata.module.parent_id</code>.
   */
  public Integer getParentId() {
    return (Integer) get(1);
  }

  /**
   * Setter for <code>mydata.module.mname</code>.
   */
  public void setMname(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>mydata.module.mname</code>.
   */
  public String getMname() {
    return (String) get(2);
  }

  /**
   * Setter for <code>mydata.module.module_type</code>.
   */
  public void setModuleType(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>mydata.module.module_type</code>.
   */
  public String getModuleType() {
    return (String) get(3);
  }

  /**
   * Setter for <code>mydata.module.is_default</code>.
   */
  public void setIsDefault(String value) {
    set(4, value);
  }

  /**
   * Getter for <code>mydata.module.is_default</code>.
   */
  public String getIsDefault() {
    return (String) get(4);
  }

  /**
   * Setter for <code>mydata.module.status</code>.
   */
  public void setStatus(String value) {
    set(5, value);
  }

  /**
   * Getter for <code>mydata.module.status</code>.
   */
  public String getStatus() {
    return (String) get(5);
  }

  /**
   * Setter for <code>mydata.module.menu_url</code>.
   */
  public void setMenuUrl(String value) {
    set(6, value);
  }

  /**
   * Getter for <code>mydata.module.menu_url</code>.
   */
  public String getMenuUrl() {
    return (String) get(6);
  }

  /**
   * Setter for <code>mydata.module.show_position</code>.
   */
  public void setShowPosition(Short value) {
    set(7, value);
  }

  /**
   * Getter for <code>mydata.module.show_position</code>.
   */
  public Short getShowPosition() {
    return (Short) get(7);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record1<Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row8<Integer, Integer, String, String, String, String, String, Short> fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row8<Integer, Integer, String, String, String, String, String, Short> valuesRow() {
    return (Row8) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field1() {
    return Module.MODULE.MID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field2() {
    return Module.MODULE.PARENT_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return Module.MODULE.MNAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field4() {
    return Module.MODULE.MODULE_TYPE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field5() {
    return Module.MODULE.IS_DEFAULT;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field6() {
    return Module.MODULE.STATUS;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field7() {
    return Module.MODULE.MENU_URL;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Short> field8() {
    return Module.MODULE.SHOW_POSITION;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component1() {
    return getMid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component2() {
    return getParentId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getMname();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component4() {
    return getModuleType();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component5() {
    return getIsDefault();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component6() {
    return getStatus();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component7() {
    return getMenuUrl();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Short component8() {
    return getShowPosition();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value1() {
    return getMid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value2() {
    return getParentId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getMname();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value4() {
    return getModuleType();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value5() {
    return getIsDefault();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value6() {
    return getStatus();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value7() {
    return getMenuUrl();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Short value8() {
    return getShowPosition();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRecord value1(Integer value) {
    setMid(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRecord value2(Integer value) {
    setParentId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRecord value3(String value) {
    setMname(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRecord value4(String value) {
    setModuleType(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRecord value5(String value) {
    setIsDefault(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRecord value6(String value) {
    setStatus(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRecord value7(String value) {
    setMenuUrl(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRecord value8(Short value) {
    setShowPosition(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRecord values(Integer value1, Integer value2, String value3, String value4,
      String value5, String value6, String value7, Short value8) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached ModuleRecord
   */
  public ModuleRecord() {
    super(Module.MODULE);
  }

  /**
   * Create a detached, initialised ModuleRecord
   */
  public ModuleRecord(Integer mid, Integer parentId, String mname, String moduleType,
      String isDefault, String status, String menuUrl, Short showPosition) {
    super(Module.MODULE);

    set(0, mid);
    set(1, parentId);
    set(2, mname);
    set(3, moduleType);
    set(4, isDefault);
    set(5, status);
    set(6, menuUrl);
    set(7, showPosition);
  }
}
