/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.records;


import cn.personal.jooq.model.jooq.tables.OperationLog;
import java.time.LocalDateTime;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * 操作日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OperationLogRecord extends TableRecordImpl<OperationLogRecord> implements
    Record8<Long, Long, String, String, String, String, LocalDateTime, String> {

  private static final long serialVersionUID = 2007197849;

  /**
   * Setter for <code>mydata.operation_log.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>mydata.operation_log.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>mydata.operation_log.login_id</code>.
   */
  public void setLoginId(Long value) {
    set(1, value);
  }

  /**
   * Getter for <code>mydata.operation_log.login_id</code>.
   */
  public Long getLoginId() {
    return (Long) get(1);
  }

  /**
   * Setter for <code>mydata.operation_log.login_name</code>.
   */
  public void setLoginName(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>mydata.operation_log.login_name</code>.
   */
  public String getLoginName() {
    return (String) get(2);
  }

  /**
   * Setter for <code>mydata.operation_log.ip_address</code>.
   */
  public void setIpAddress(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>mydata.operation_log.ip_address</code>.
   */
  public String getIpAddress() {
    return (String) get(3);
  }

  /**
   * Setter for <code>mydata.operation_log.method_name</code>.
   */
  public void setMethodName(String value) {
    set(4, value);
  }

  /**
   * Getter for <code>mydata.operation_log.method_name</code>.
   */
  public String getMethodName() {
    return (String) get(4);
  }

  /**
   * Setter for <code>mydata.operation_log.method_remark</code>.
   */
  public void setMethodRemark(String value) {
    set(5, value);
  }

  /**
   * Getter for <code>mydata.operation_log.method_remark</code>.
   */
  public String getMethodRemark() {
    return (String) get(5);
  }

  /**
   * Setter for <code>mydata.operation_log.opt_date</code>.
   */
  public void setOptDate(LocalDateTime value) {
    set(6, value);
  }

  /**
   * Getter for <code>mydata.operation_log.opt_date</code>.
   */
  public LocalDateTime getOptDate() {
    return (LocalDateTime) get(6);
  }

  /**
   * Setter for <code>mydata.operation_log.operating_content</code>.
   */
  public void setOperatingContent(String value) {
    set(7, value);
  }

  /**
   * Getter for <code>mydata.operation_log.operating_content</code>.
   */
  public String getOperatingContent() {
    return (String) get(7);
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row8<Long, Long, String, String, String, String, LocalDateTime, String> fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row8<Long, Long, String, String, String, String, LocalDateTime, String> valuesRow() {
    return (Row8) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field1() {
    return OperationLog.OPERATION_LOG.ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field2() {
    return OperationLog.OPERATION_LOG.LOGIN_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return OperationLog.OPERATION_LOG.LOGIN_NAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field4() {
    return OperationLog.OPERATION_LOG.IP_ADDRESS;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field5() {
    return OperationLog.OPERATION_LOG.METHOD_NAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field6() {
    return OperationLog.OPERATION_LOG.METHOD_REMARK;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field7() {
    return OperationLog.OPERATION_LOG.OPT_DATE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field8() {
    return OperationLog.OPERATION_LOG.OPERATING_CONTENT;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component2() {
    return getLoginId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getLoginName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component4() {
    return getIpAddress();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component5() {
    return getMethodName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component6() {
    return getMethodRemark();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component7() {
    return getOptDate();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component8() {
    return getOperatingContent();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value2() {
    return getLoginId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getLoginName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value4() {
    return getIpAddress();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value5() {
    return getMethodName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value6() {
    return getMethodRemark();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value7() {
    return getOptDate();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value8() {
    return getOperatingContent();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OperationLogRecord value1(Long value) {
    setId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OperationLogRecord value2(Long value) {
    setLoginId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OperationLogRecord value3(String value) {
    setLoginName(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OperationLogRecord value4(String value) {
    setIpAddress(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OperationLogRecord value5(String value) {
    setMethodName(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OperationLogRecord value6(String value) {
    setMethodRemark(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OperationLogRecord value7(LocalDateTime value) {
    setOptDate(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OperationLogRecord value8(String value) {
    setOperatingContent(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OperationLogRecord values(Long value1, Long value2, String value3, String value4,
      String value5, String value6, LocalDateTime value7, String value8) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached OperationLogRecord
   */
  public OperationLogRecord() {
    super(OperationLog.OPERATION_LOG);
  }

  /**
   * Create a detached, initialised OperationLogRecord
   */
  public OperationLogRecord(Long id, Long loginId, String loginName, String ipAddress,
      String methodName, String methodRemark, LocalDateTime optDate, String operatingContent) {
    super(OperationLog.OPERATION_LOG);

    set(0, id);
    set(1, loginId);
    set(2, loginName);
    set(3, ipAddress);
    set(4, methodName);
    set(5, methodRemark);
    set(6, optDate);
    set(7, operatingContent);
  }
}
