/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.records;


import cn.personal.jooq.model.jooq.tables.PortalResource;
import java.time.LocalDateTime;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PortalResourceRecord extends UpdatableRecordImpl<PortalResourceRecord> implements
    Record5<Long, Long, String, String, LocalDateTime> {

  private static final long serialVersionUID = -1937562347;

  /**
   * Setter for <code>mydata.portal_resource.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>mydata.portal_resource.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>mydata.portal_resource.shelf_user_id</code>.
   */
  public void setShelfUserId(Long value) {
    set(1, value);
  }

  /**
   * Getter for <code>mydata.portal_resource.shelf_user_id</code>.
   */
  public Long getShelfUserId() {
    return (Long) get(1);
  }

  /**
   * Setter for <code>mydata.portal_resource.shelf_user_name</code>. 上架人名称
   */
  public void setShelfUserName(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>mydata.portal_resource.shelf_user_name</code>. 上架人名称
   */
  public String getShelfUserName() {
    return (String) get(2);
  }

  /**
   * Setter for <code>mydata.portal_resource.portal_name</code>.
   */
  public void setPortalName(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>mydata.portal_resource.portal_name</code>.
   */
  public String getPortalName() {
    return (String) get(3);
  }

  /**
   * Setter for <code>mydata.portal_resource.create_time</code>.
   */
  public void setCreateTime(LocalDateTime value) {
    set(4, value);
  }

  /**
   * Getter for <code>mydata.portal_resource.create_time</code>.
   */
  public LocalDateTime getCreateTime() {
    return (LocalDateTime) get(4);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record5 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row5<Long, Long, String, String, LocalDateTime> fieldsRow() {
    return (Row5) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row5<Long, Long, String, String, LocalDateTime> valuesRow() {
    return (Row5) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field1() {
    return PortalResource.PORTAL_RESOURCE.ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field2() {
    return PortalResource.PORTAL_RESOURCE.SHELF_USER_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return PortalResource.PORTAL_RESOURCE.SHELF_USER_NAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field4() {
    return PortalResource.PORTAL_RESOURCE.PORTAL_NAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field5() {
    return PortalResource.PORTAL_RESOURCE.CREATE_TIME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component2() {
    return getShelfUserId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getShelfUserName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component4() {
    return getPortalName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component5() {
    return getCreateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value2() {
    return getShelfUserId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getShelfUserName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value4() {
    return getPortalName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value5() {
    return getCreateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PortalResourceRecord value1(Long value) {
    setId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PortalResourceRecord value2(Long value) {
    setShelfUserId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PortalResourceRecord value3(String value) {
    setShelfUserName(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PortalResourceRecord value4(String value) {
    setPortalName(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PortalResourceRecord value5(LocalDateTime value) {
    setCreateTime(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PortalResourceRecord values(Long value1, Long value2, String value3, String value4,
      LocalDateTime value5) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached PortalResourceRecord
   */
  public PortalResourceRecord() {
    super(PortalResource.PORTAL_RESOURCE);
  }

  /**
   * Create a detached, initialised PortalResourceRecord
   */
  public PortalResourceRecord(Long id, Long shelfUserId, String shelfUserName, String portalName,
      LocalDateTime createTime) {
    super(PortalResource.PORTAL_RESOURCE);

    set(0, id);
    set(1, shelfUserId);
    set(2, shelfUserName);
    set(3, portalName);
    set(4, createTime);
  }
}
