/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.records;


import cn.personal.jooq.model.jooq.tables.Product;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProductRecord extends TableRecordImpl<ProductRecord> implements
    Record5<Long, String, String, String, Integer> {

  private static final long serialVersionUID = 1447573055;

  /**
   * Setter for <code>mydata.product.id</code>. id
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>mydata.product.id</code>. id
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>mydata.product.productName</code>. 产品名称
   */
  public void setProductname(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>mydata.product.productName</code>. 产品名称
   */
  public String getProductname() {
    return (String) get(1);
  }

  /**
   * Setter for <code>mydata.product.productContent</code>. 产品内容
   */
  public void setProductcontent(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>mydata.product.productContent</code>. 产品内容
   */
  public String getProductcontent() {
    return (String) get(2);
  }

  /**
   * Setter for <code>mydata.product.price</code>. 价格
   */
  public void setPrice(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>mydata.product.price</code>. 价格
   */
  public String getPrice() {
    return (String) get(3);
  }

  /**
   * Setter for <code>mydata.product.sort</code>. 排序
   */
  public void setSort(Integer value) {
    set(4, value);
  }

  /**
   * Getter for <code>mydata.product.sort</code>. 排序
   */
  public Integer getSort() {
    return (Integer) get(4);
  }

  // -------------------------------------------------------------------------
  // Record5 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row5<Long, String, String, String, Integer> fieldsRow() {
    return (Row5) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row5<Long, String, String, String, Integer> valuesRow() {
    return (Row5) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field1() {
    return Product.PRODUCT.ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field2() {
    return Product.PRODUCT.PRODUCTNAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return Product.PRODUCT.PRODUCTCONTENT;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field4() {
    return Product.PRODUCT.PRICE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field5() {
    return Product.PRODUCT.SORT;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component2() {
    return getProductname();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getProductcontent();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component4() {
    return getPrice();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component5() {
    return getSort();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value2() {
    return getProductname();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getProductcontent();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value4() {
    return getPrice();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value5() {
    return getSort();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ProductRecord value1(Long value) {
    setId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ProductRecord value2(String value) {
    setProductname(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ProductRecord value3(String value) {
    setProductcontent(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ProductRecord value4(String value) {
    setPrice(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ProductRecord value5(Integer value) {
    setSort(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ProductRecord values(Long value1, String value2, String value3, String value4,
      Integer value5) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached ProductRecord
   */
  public ProductRecord() {
    super(Product.PRODUCT);
  }

  /**
   * Create a detached, initialised ProductRecord
   */
  public ProductRecord(Long id, String productname, String productcontent, String price,
      Integer sort) {
    super(Product.PRODUCT);

    set(0, id);
    set(1, productname);
    set(2, productcontent);
    set(3, price);
    set(4, sort);
  }
}
