/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.records;


import cn.personal.jooq.model.jooq.tables.UserRole;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserRoleRecord extends TableRecordImpl<UserRoleRecord> implements
    Record2<Integer, Integer> {

  private static final long serialVersionUID = -1061463233;

  /**
   * Setter for <code>mydata.user_role.uid</code>.
   */
  public void setUid(Integer value) {
    set(0, value);
  }

  /**
   * Getter for <code>mydata.user_role.uid</code>.
   */
  public Integer getUid() {
    return (Integer) get(0);
  }

  /**
   * Setter for <code>mydata.user_role.rid</code>.
   */
  public void setRid(Integer value) {
    set(1, value);
  }

  /**
   * Getter for <code>mydata.user_role.rid</code>.
   */
  public Integer getRid() {
    return (Integer) get(1);
  }

  // -------------------------------------------------------------------------
  // Record2 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row2<Integer, Integer> fieldsRow() {
    return (Row2) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row2<Integer, Integer> valuesRow() {
    return (Row2) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field1() {
    return UserRole.USER_ROLE.UID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field2() {
    return UserRole.USER_ROLE.RID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component1() {
    return getUid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component2() {
    return getRid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value1() {
    return getUid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value2() {
    return getRid();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public UserRoleRecord value1(Integer value) {
    setUid(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public UserRoleRecord value2(Integer value) {
    setRid(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public UserRoleRecord values(Integer value1, Integer value2) {
    value1(value1);
    value2(value2);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached UserRoleRecord
   */
  public UserRoleRecord() {
    super(UserRole.USER_ROLE);
  }

  /**
   * Create a detached, initialised UserRoleRecord
   */
  public UserRoleRecord(Integer uid, Integer rid) {
    super(UserRole.USER_ROLE);

    set(0, uid);
    set(1, rid);
  }
}
