/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.daos;


import cn.personal.jooq.model.jooq.tables.LoginUserInformation;
import cn.personal.jooq.model.jooq.tables.records.LoginUserInformationRecord;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LoginUserInformationDao extends
    DAOImpl<LoginUserInformationRecord, cn.personal.jooq.model.jooq.tables.pojos.LoginUserInformation, Integer> {

  /**
   * Create a new LoginUserInformationDao without any configuration
   */
  public LoginUserInformationDao() {
    super(LoginUserInformation.LOGIN_USER_INFORMATION,
        cn.personal.jooq.model.jooq.tables.pojos.LoginUserInformation.class);
  }

  /**
   * Create a new LoginUserInformationDao with an attached configuration
   */
  public LoginUserInformationDao(Configuration configuration) {
    super(LoginUserInformation.LOGIN_USER_INFORMATION,
        cn.personal.jooq.model.jooq.tables.pojos.LoginUserInformation.class, configuration);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  protected Integer getId(cn.personal.jooq.model.jooq.tables.pojos.LoginUserInformation object) {
    return object.getId();
  }

  /**
   * Fetch records that have <code>id IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.LoginUserInformation> fetchById(
      Integer... values) {
    return fetch(LoginUserInformation.LOGIN_USER_INFORMATION.ID, values);
  }

  /**
   * Fetch a unique record that has <code>id = value</code>
   */
  public cn.personal.jooq.model.jooq.tables.pojos.LoginUserInformation fetchOneById(Integer value) {
    return fetchOne(LoginUserInformation.LOGIN_USER_INFORMATION.ID, value);
  }

  /**
   * Fetch records that have <code>user_id IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.LoginUserInformation> fetchByUserId(
      Long... values) {
    return fetch(LoginUserInformation.LOGIN_USER_INFORMATION.USER_ID, values);
  }

  /**
   * Fetch records that have <code>account IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.LoginUserInformation> fetchByAccount(
      String... values) {
    return fetch(LoginUserInformation.LOGIN_USER_INFORMATION.ACCOUNT, values);
  }

  /**
   * Fetch records that have <code>password IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.LoginUserInformation> fetchByPassword(
      String... values) {
    return fetch(LoginUserInformation.LOGIN_USER_INFORMATION.PASSWORD, values);
  }
}
