/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.daos;


import cn.personal.jooq.model.jooq.tables.Module;
import cn.personal.jooq.model.jooq.tables.records.ModuleRecord;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ModuleDao extends
    DAOImpl<ModuleRecord, cn.personal.jooq.model.jooq.tables.pojos.Module, Integer> {

  /**
   * Create a new ModuleDao without any configuration
   */
  public ModuleDao() {
    super(Module.MODULE, cn.personal.jooq.model.jooq.tables.pojos.Module.class);
  }

  /**
   * Create a new ModuleDao with an attached configuration
   */
  public ModuleDao(Configuration configuration) {
    super(Module.MODULE, cn.personal.jooq.model.jooq.tables.pojos.Module.class, configuration);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  protected Integer getId(cn.personal.jooq.model.jooq.tables.pojos.Module object) {
    return object.getMid();
  }

  /**
   * Fetch records that have <code>mid IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.Module> fetchByMid(Integer... values) {
    return fetch(Module.MODULE.MID, values);
  }

  /**
   * Fetch a unique record that has <code>mid = value</code>
   */
  public cn.personal.jooq.model.jooq.tables.pojos.Module fetchOneByMid(Integer value) {
    return fetchOne(Module.MODULE.MID, value);
  }

  /**
   * Fetch records that have <code>parent_id IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.Module> fetchByParentId(Integer... values) {
    return fetch(Module.MODULE.PARENT_ID, values);
  }

  /**
   * Fetch records that have <code>mname IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.Module> fetchByMname(String... values) {
    return fetch(Module.MODULE.MNAME, values);
  }

  /**
   * Fetch records that have <code>module_type IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.Module> fetchByModuleType(String... values) {
    return fetch(Module.MODULE.MODULE_TYPE, values);
  }

  /**
   * Fetch records that have <code>is_default IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.Module> fetchByIsDefault(String... values) {
    return fetch(Module.MODULE.IS_DEFAULT, values);
  }

  /**
   * Fetch records that have <code>status IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.Module> fetchByStatus(String... values) {
    return fetch(Module.MODULE.STATUS, values);
  }

  /**
   * Fetch records that have <code>menu_url IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.Module> fetchByMenuUrl(String... values) {
    return fetch(Module.MODULE.MENU_URL, values);
  }

  /**
   * Fetch records that have <code>show_position IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.Module> fetchByShowPosition(
      Short... values) {
    return fetch(Module.MODULE.SHOW_POSITION, values);
  }
}
