/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.daos;


import cn.personal.jooq.model.jooq.tables.MycatSeqlg;
import cn.personal.jooq.model.jooq.tables.records.MycatSeqlgRecord;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MycatSeqlgDao extends
    DAOImpl<MycatSeqlgRecord, cn.personal.jooq.model.jooq.tables.pojos.MycatSeqlg, String> {

  /**
   * Create a new MycatSeqlgDao without any configuration
   */
  public MycatSeqlgDao() {
    super(MycatSeqlg.MYCAT_SEQLG, cn.personal.jooq.model.jooq.tables.pojos.MycatSeqlg.class);
  }

  /**
   * Create a new MycatSeqlgDao with an attached configuration
   */
  public MycatSeqlgDao(Configuration configuration) {
    super(MycatSeqlg.MYCAT_SEQLG, cn.personal.jooq.model.jooq.tables.pojos.MycatSeqlg.class,
        configuration);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  protected String getId(cn.personal.jooq.model.jooq.tables.pojos.MycatSeqlg object) {
    return object.getName();
  }

  /**
   * Fetch records that have <code>name IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.MycatSeqlg> fetchByName(String... values) {
    return fetch(MycatSeqlg.MYCAT_SEQLG.NAME, values);
  }

  /**
   * Fetch a unique record that has <code>name = value</code>
   */
  public cn.personal.jooq.model.jooq.tables.pojos.MycatSeqlg fetchOneByName(String value) {
    return fetchOne(MycatSeqlg.MYCAT_SEQLG.NAME, value);
  }

  /**
   * Fetch records that have <code>current_value IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.MycatSeqlg> fetchByCurrentValue(
      Integer... values) {
    return fetch(MycatSeqlg.MYCAT_SEQLG.CURRENT_VALUE, values);
  }

  /**
   * Fetch records that have <code>increment IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.MycatSeqlg> fetchByIncrement(
      Integer... values) {
    return fetch(MycatSeqlg.MYCAT_SEQLG.INCREMENT, values);
  }
}
