/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.daos;


import cn.personal.jooq.model.jooq.tables.PUser;
import cn.personal.jooq.model.jooq.tables.records.PUserRecord;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PUserDao extends
    DAOImpl<PUserRecord, cn.personal.jooq.model.jooq.tables.pojos.PUser, Integer> {

  /**
   * Create a new PUserDao without any configuration
   */
  public PUserDao() {
    super(PUser.P_USER, cn.personal.jooq.model.jooq.tables.pojos.PUser.class);
  }

  /**
   * Create a new PUserDao with an attached configuration
   */
  public PUserDao(Configuration configuration) {
    super(PUser.P_USER, cn.personal.jooq.model.jooq.tables.pojos.PUser.class, configuration);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  protected Integer getId(cn.personal.jooq.model.jooq.tables.pojos.PUser object) {
    return object.getUid();
  }

  /**
   * Fetch records that have <code>uid IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.PUser> fetchByUid(Integer... values) {
    return fetch(PUser.P_USER.UID, values);
  }

  /**
   * Fetch a unique record that has <code>uid = value</code>
   */
  public cn.personal.jooq.model.jooq.tables.pojos.PUser fetchOneByUid(Integer value) {
    return fetchOne(PUser.P_USER.UID, value);
  }

  /**
   * Fetch records that have <code>username IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.PUser> fetchByUsername(String... values) {
    return fetch(PUser.P_USER.USERNAME, values);
  }

  /**
   * Fetch records that have <code>password IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.PUser> fetchByPassword(String... values) {
    return fetch(PUser.P_USER.PASSWORD, values);
  }

  /**
   * Fetch records that have <code>uname IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.PUser> fetchByUname(String... values) {
    return fetch(PUser.P_USER.UNAME, values);
  }

  /**
   * Fetch records that have <code>age IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.PUser> fetchByAge(Integer... values) {
    return fetch(PUser.P_USER.AGE, values);
  }

  /**
   * Fetch records that have <code>sex IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.PUser> fetchBySex(String... values) {
    return fetch(PUser.P_USER.SEX, values);
  }

  /**
   * Fetch records that have <code>address IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.PUser> fetchByAddress(String... values) {
    return fetch(PUser.P_USER.ADDRESS, values);
  }

  /**
   * Fetch records that have <code>version IN (values)</code>
   */
  public List<cn.personal.jooq.model.jooq.tables.pojos.PUser> fetchByVersion(Integer... values) {
    return fetch(PUser.P_USER.VERSION, values);
  }
}
