/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq;


import cn.personal.jooq.model.jooq.tables.DemoInfo;
import cn.personal.jooq.model.jooq.tables.LgUserAmount;
import cn.personal.jooq.model.jooq.tables.LoginUserInformation;
import cn.personal.jooq.model.jooq.tables.Module;
import cn.personal.jooq.model.jooq.tables.ModuleRole;
import cn.personal.jooq.model.jooq.tables.MycatSeqlg;
import cn.personal.jooq.model.jooq.tables.PUser;
import cn.personal.jooq.model.jooq.tables.PortalResource;
import cn.personal.jooq.model.jooq.tables.Role;
import cn.personal.jooq.model.jooq.tables.UserRole;
import javax.annotation.Generated;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>mydata</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index DEMO_INFO_PRIMARY = Indexes0.DEMO_INFO_PRIMARY;
  public static final Index LG_USER_AMOUNT_PRIMARY = Indexes0.LG_USER_AMOUNT_PRIMARY;
  public static final Index LOGIN_USER_INFORMATION_PRIMARY = Indexes0.LOGIN_USER_INFORMATION_PRIMARY;
  public static final Index MODULE_PRIMARY = Indexes0.MODULE_PRIMARY;
  public static final Index MODULE_ROLE_MID = Indexes0.MODULE_ROLE_MID;
  public static final Index MODULE_ROLE_RID = Indexes0.MODULE_ROLE_RID;
  public static final Index MYCAT_SEQLG_PRIMARY = Indexes0.MYCAT_SEQLG_PRIMARY;
  public static final Index PORTAL_RESOURCE_PRIMARY = Indexes0.PORTAL_RESOURCE_PRIMARY;
  public static final Index P_USER_PRIMARY = Indexes0.P_USER_PRIMARY;
  public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
  public static final Index USER_ROLE_R_FK = Indexes0.USER_ROLE_R_FK;
  public static final Index USER_ROLE_U_FK = Indexes0.USER_ROLE_U_FK;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Indexes0 {

    public static Index DEMO_INFO_PRIMARY = Internal
        .createIndex("PRIMARY", DemoInfo.DEMO_INFO, new OrderField[]{DemoInfo.DEMO_INFO.ID}, true);
    public static Index LG_USER_AMOUNT_PRIMARY = Internal
        .createIndex("PRIMARY", LgUserAmount.LG_USER_AMOUNT,
            new OrderField[]{LgUserAmount.LG_USER_AMOUNT.ID}, true);
    public static Index LOGIN_USER_INFORMATION_PRIMARY = Internal
        .createIndex("PRIMARY", LoginUserInformation.LOGIN_USER_INFORMATION,
            new OrderField[]{LoginUserInformation.LOGIN_USER_INFORMATION.ID}, true);
    public static Index MODULE_PRIMARY = Internal
        .createIndex("PRIMARY", Module.MODULE, new OrderField[]{Module.MODULE.MID}, true);
    public static Index MODULE_ROLE_MID = Internal
        .createIndex("mid", ModuleRole.MODULE_ROLE, new OrderField[]{ModuleRole.MODULE_ROLE.MID},
            false);
    public static Index MODULE_ROLE_RID = Internal
        .createIndex("rid", ModuleRole.MODULE_ROLE, new OrderField[]{ModuleRole.MODULE_ROLE.RID},
            false);
    public static Index MYCAT_SEQLG_PRIMARY = Internal
        .createIndex("PRIMARY", MycatSeqlg.MYCAT_SEQLG,
            new OrderField[]{MycatSeqlg.MYCAT_SEQLG.NAME}, true);
    public static Index PORTAL_RESOURCE_PRIMARY = Internal
        .createIndex("PRIMARY", PortalResource.PORTAL_RESOURCE,
            new OrderField[]{PortalResource.PORTAL_RESOURCE.ID}, true);
    public static Index P_USER_PRIMARY = Internal
        .createIndex("PRIMARY", PUser.P_USER, new OrderField[]{PUser.P_USER.UID}, true);
    public static Index ROLE_PRIMARY = Internal
        .createIndex("PRIMARY", Role.ROLE, new OrderField[]{Role.ROLE.RID}, true);
    public static Index USER_ROLE_R_FK = Internal
        .createIndex("r_fk", UserRole.USER_ROLE, new OrderField[]{UserRole.USER_ROLE.RID}, false);
    public static Index USER_ROLE_U_FK = Internal
        .createIndex("u_fk", UserRole.USER_ROLE, new OrderField[]{UserRole.USER_ROLE.UID}, false);
  }
}
