/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq;


import cn.personal.jooq.model.jooq.tables.DemoInfo;
import cn.personal.jooq.model.jooq.tables.LgUserAmount;
import cn.personal.jooq.model.jooq.tables.LoginUserInformation;
import cn.personal.jooq.model.jooq.tables.Module;
import cn.personal.jooq.model.jooq.tables.ModuleRole;
import cn.personal.jooq.model.jooq.tables.MycatSeqlg;
import cn.personal.jooq.model.jooq.tables.PUser;
import cn.personal.jooq.model.jooq.tables.PortalResource;
import cn.personal.jooq.model.jooq.tables.Role;
import cn.personal.jooq.model.jooq.tables.UserRole;
import cn.personal.jooq.model.jooq.tables.records.DemoInfoRecord;
import cn.personal.jooq.model.jooq.tables.records.LgUserAmountRecord;
import cn.personal.jooq.model.jooq.tables.records.LoginUserInformationRecord;
import cn.personal.jooq.model.jooq.tables.records.ModuleRecord;
import cn.personal.jooq.model.jooq.tables.records.ModuleRoleRecord;
import cn.personal.jooq.model.jooq.tables.records.MycatSeqlgRecord;
import cn.personal.jooq.model.jooq.tables.records.PUserRecord;
import cn.personal.jooq.model.jooq.tables.records.PortalResourceRecord;
import cn.personal.jooq.model.jooq.tables.records.RoleRecord;
import cn.personal.jooq.model.jooq.tables.records.UserRoleRecord;
import javax.annotation.Generated;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of the <code>mydata</code>
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------

  public static final Identity<LoginUserInformationRecord, Integer> IDENTITY_LOGIN_USER_INFORMATION = Identities0.IDENTITY_LOGIN_USER_INFORMATION;
  public static final Identity<ModuleRecord, Integer> IDENTITY_MODULE = Identities0.IDENTITY_MODULE;
  public static final Identity<PortalResourceRecord, Long> IDENTITY_PORTAL_RESOURCE = Identities0.IDENTITY_PORTAL_RESOURCE;
  public static final Identity<PUserRecord, Integer> IDENTITY_P_USER = Identities0.IDENTITY_P_USER;
  public static final Identity<RoleRecord, Integer> IDENTITY_ROLE = Identities0.IDENTITY_ROLE;

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<DemoInfoRecord> KEY_DEMO_INFO_PRIMARY = UniqueKeys0.KEY_DEMO_INFO_PRIMARY;
  public static final UniqueKey<LgUserAmountRecord> KEY_LG_USER_AMOUNT_PRIMARY = UniqueKeys0.KEY_LG_USER_AMOUNT_PRIMARY;
  public static final UniqueKey<LoginUserInformationRecord> KEY_LOGIN_USER_INFORMATION_PRIMARY = UniqueKeys0.KEY_LOGIN_USER_INFORMATION_PRIMARY;
  public static final UniqueKey<ModuleRecord> KEY_MODULE_PRIMARY = UniqueKeys0.KEY_MODULE_PRIMARY;
  public static final UniqueKey<MycatSeqlgRecord> KEY_MYCAT_SEQLG_PRIMARY = UniqueKeys0.KEY_MYCAT_SEQLG_PRIMARY;
  public static final UniqueKey<PortalResourceRecord> KEY_PORTAL_RESOURCE_PRIMARY = UniqueKeys0.KEY_PORTAL_RESOURCE_PRIMARY;
  public static final UniqueKey<PUserRecord> KEY_P_USER_PRIMARY = UniqueKeys0.KEY_P_USER_PRIMARY;
  public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = UniqueKeys0.KEY_ROLE_PRIMARY;

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  public static final ForeignKey<ModuleRoleRecord, RoleRecord> RID = ForeignKeys0.RID;
  public static final ForeignKey<ModuleRoleRecord, ModuleRecord> MID = ForeignKeys0.MID;
  public static final ForeignKey<UserRoleRecord, PUserRecord> U_FK = ForeignKeys0.U_FK;
  public static final ForeignKey<UserRoleRecord, RoleRecord> R_FK = ForeignKeys0.R_FK;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Identities0 {

    public static Identity<LoginUserInformationRecord, Integer> IDENTITY_LOGIN_USER_INFORMATION = Internal
        .createIdentity(LoginUserInformation.LOGIN_USER_INFORMATION,
            LoginUserInformation.LOGIN_USER_INFORMATION.ID);
    public static Identity<ModuleRecord, Integer> IDENTITY_MODULE = Internal
        .createIdentity(Module.MODULE, Module.MODULE.MID);
    public static Identity<PortalResourceRecord, Long> IDENTITY_PORTAL_RESOURCE = Internal
        .createIdentity(PortalResource.PORTAL_RESOURCE, PortalResource.PORTAL_RESOURCE.ID);
    public static Identity<PUserRecord, Integer> IDENTITY_P_USER = Internal
        .createIdentity(PUser.P_USER, PUser.P_USER.UID);
    public static Identity<RoleRecord, Integer> IDENTITY_ROLE = Internal
        .createIdentity(Role.ROLE, Role.ROLE.RID);
  }

  private static class UniqueKeys0 {

    public static final UniqueKey<DemoInfoRecord> KEY_DEMO_INFO_PRIMARY = Internal
        .createUniqueKey(DemoInfo.DEMO_INFO, "KEY_demo_info_PRIMARY", DemoInfo.DEMO_INFO.ID);
    public static final UniqueKey<LgUserAmountRecord> KEY_LG_USER_AMOUNT_PRIMARY = Internal
        .createUniqueKey(LgUserAmount.LG_USER_AMOUNT, "KEY_lg_user_amount_PRIMARY",
            LgUserAmount.LG_USER_AMOUNT.ID);
    public static final UniqueKey<LoginUserInformationRecord> KEY_LOGIN_USER_INFORMATION_PRIMARY = Internal
        .createUniqueKey(LoginUserInformation.LOGIN_USER_INFORMATION,
            "KEY_login_user_information_PRIMARY", LoginUserInformation.LOGIN_USER_INFORMATION.ID);
    public static final UniqueKey<ModuleRecord> KEY_MODULE_PRIMARY = Internal
        .createUniqueKey(Module.MODULE, "KEY_module_PRIMARY", Module.MODULE.MID);
    public static final UniqueKey<MycatSeqlgRecord> KEY_MYCAT_SEQLG_PRIMARY = Internal
        .createUniqueKey(MycatSeqlg.MYCAT_SEQLG, "KEY_mycat_seqlg_PRIMARY",
            MycatSeqlg.MYCAT_SEQLG.NAME);
    public static final UniqueKey<PortalResourceRecord> KEY_PORTAL_RESOURCE_PRIMARY = Internal
        .createUniqueKey(PortalResource.PORTAL_RESOURCE, "KEY_portal_resource_PRIMARY",
            PortalResource.PORTAL_RESOURCE.ID);
    public static final UniqueKey<PUserRecord> KEY_P_USER_PRIMARY = Internal
        .createUniqueKey(PUser.P_USER, "KEY_p_user_PRIMARY", PUser.P_USER.UID);
    public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = Internal
        .createUniqueKey(Role.ROLE, "KEY_role_PRIMARY", Role.ROLE.RID);
  }

  private static class ForeignKeys0 {

    public static final ForeignKey<ModuleRoleRecord, RoleRecord> RID = Internal
        .createForeignKey(cn.personal.jooq.model.jooq.Keys.KEY_ROLE_PRIMARY, ModuleRole.MODULE_ROLE,
            "rid", ModuleRole.MODULE_ROLE.RID);
    public static final ForeignKey<ModuleRoleRecord, ModuleRecord> MID = Internal
        .createForeignKey(cn.personal.jooq.model.jooq.Keys.KEY_MODULE_PRIMARY,
            ModuleRole.MODULE_ROLE, "mid", ModuleRole.MODULE_ROLE.MID);
    public static final ForeignKey<UserRoleRecord, PUserRecord> U_FK = Internal
        .createForeignKey(cn.personal.jooq.model.jooq.Keys.KEY_P_USER_PRIMARY, UserRole.USER_ROLE,
            "u_fk", UserRole.USER_ROLE.UID);
    public static final ForeignKey<UserRoleRecord, RoleRecord> R_FK = Internal
        .createForeignKey(cn.personal.jooq.model.jooq.Keys.KEY_ROLE_PRIMARY, UserRole.USER_ROLE,
            "r_fk", UserRole.USER_ROLE.RID);
  }
}
