/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq;


import cn.personal.jooq.model.jooq.tables.DemoInfo;
import cn.personal.jooq.model.jooq.tables.HibernateSequence;
import cn.personal.jooq.model.jooq.tables.LgUserAmount;
import cn.personal.jooq.model.jooq.tables.LoginUserInformation;
import cn.personal.jooq.model.jooq.tables.Module;
import cn.personal.jooq.model.jooq.tables.ModuleRole;
import cn.personal.jooq.model.jooq.tables.MycatSeqlg;
import cn.personal.jooq.model.jooq.tables.OperationLog;
import cn.personal.jooq.model.jooq.tables.PUser;
import cn.personal.jooq.model.jooq.tables.PortalResource;
import cn.personal.jooq.model.jooq.tables.Product;
import cn.personal.jooq.model.jooq.tables.Role;
import cn.personal.jooq.model.jooq.tables.UserRole;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Mydata extends SchemaImpl {

  private static final long serialVersionUID = 581668750;

  /**
   * The reference instance of <code>mydata</code>
   */
  public static final Mydata MYDATA = new Mydata();

  /**
   * The table <code>mydata.demo_info</code>.
   */
  public final DemoInfo DEMO_INFO = cn.personal.jooq.model.jooq.tables.DemoInfo.DEMO_INFO;

  /**
   * The table <code>mydata.hibernate_sequence</code>.
   */
  public final HibernateSequence HIBERNATE_SEQUENCE = cn.personal.jooq.model.jooq.tables.HibernateSequence.HIBERNATE_SEQUENCE;

  /**
   * 用户资产表
   */
  public final LgUserAmount LG_USER_AMOUNT = cn.personal.jooq.model.jooq.tables.LgUserAmount.LG_USER_AMOUNT;

  /**
   * The table <code>mydata.login_user_information</code>.
   */
  public final LoginUserInformation LOGIN_USER_INFORMATION = cn.personal.jooq.model.jooq.tables.LoginUserInformation.LOGIN_USER_INFORMATION;

  /**
   * The table <code>mydata.module</code>.
   */
  public final Module MODULE = cn.personal.jooq.model.jooq.tables.Module.MODULE;

  /**
   * The table <code>mydata.module_role</code>.
   */
  public final ModuleRole MODULE_ROLE = cn.personal.jooq.model.jooq.tables.ModuleRole.MODULE_ROLE;

  /**
   * The table <code>mydata.mycat_seqlg</code>.
   */
  public final MycatSeqlg MYCAT_SEQLG = cn.personal.jooq.model.jooq.tables.MycatSeqlg.MYCAT_SEQLG;

  /**
   * 操作日志表
   */
  public final OperationLog OPERATION_LOG = cn.personal.jooq.model.jooq.tables.OperationLog.OPERATION_LOG;

  /**
   * The table <code>mydata.portal_resource</code>.
   */
  public final PortalResource PORTAL_RESOURCE = cn.personal.jooq.model.jooq.tables.PortalResource.PORTAL_RESOURCE;

  /**
   * The table <code>mydata.product</code>.
   */
  public final Product PRODUCT = cn.personal.jooq.model.jooq.tables.Product.PRODUCT;

  /**
   * The table <code>mydata.p_user</code>.
   */
  public final PUser P_USER = cn.personal.jooq.model.jooq.tables.PUser.P_USER;

  /**
   * The table <code>mydata.role</code>.
   */
  public final Role ROLE = cn.personal.jooq.model.jooq.tables.Role.ROLE;

  /**
   * The table <code>mydata.user_role</code>.
   */
  public final UserRole USER_ROLE = cn.personal.jooq.model.jooq.tables.UserRole.USER_ROLE;

  /**
   * No further instances allowed
   */
  private Mydata() {
    super("mydata", null);
  }


  /**
   * {@inheritDoc}
   */
  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    List result = new ArrayList();
    result.addAll(getTables0());
    return result;
  }

  private final List<Table<?>> getTables0() {
    return Arrays.<Table<?>>asList(
        DemoInfo.DEMO_INFO,
        HibernateSequence.HIBERNATE_SEQUENCE,
        LgUserAmount.LG_USER_AMOUNT,
        LoginUserInformation.LOGIN_USER_INFORMATION,
        Module.MODULE,
        ModuleRole.MODULE_ROLE,
        MycatSeqlg.MYCAT_SEQLG,
        OperationLog.OPERATION_LOG,
        PortalResource.PORTAL_RESOURCE,
        Product.PRODUCT,
        PUser.P_USER,
        Role.ROLE,
        UserRole.USER_ROLE);
  }
}
