/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq;


import cn.personal.jooq.model.jooq.tables.DemoInfo;
import cn.personal.jooq.model.jooq.tables.HibernateSequence;
import cn.personal.jooq.model.jooq.tables.LgUserAmount;
import cn.personal.jooq.model.jooq.tables.LoginUserInformation;
import cn.personal.jooq.model.jooq.tables.Module;
import cn.personal.jooq.model.jooq.tables.ModuleRole;
import cn.personal.jooq.model.jooq.tables.MycatSeqlg;
import cn.personal.jooq.model.jooq.tables.OperationLog;
import cn.personal.jooq.model.jooq.tables.PUser;
import cn.personal.jooq.model.jooq.tables.PortalResource;
import cn.personal.jooq.model.jooq.tables.Product;
import cn.personal.jooq.model.jooq.tables.Role;
import cn.personal.jooq.model.jooq.tables.UserRole;
import javax.annotation.Generated;


/**
 * Convenience access to all tables in mydata
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

  /**
   * The table <code>mydata.demo_info</code>.
   */
  public static final DemoInfo DEMO_INFO = cn.personal.jooq.model.jooq.tables.DemoInfo.DEMO_INFO;

  /**
   * The table <code>mydata.hibernate_sequence</code>.
   */
  public static final HibernateSequence HIBERNATE_SEQUENCE = cn.personal.jooq.model.jooq.tables.HibernateSequence.HIBERNATE_SEQUENCE;

  /**
   * 用户资产表
   */
  public static final LgUserAmount LG_USER_AMOUNT = cn.personal.jooq.model.jooq.tables.LgUserAmount.LG_USER_AMOUNT;

  /**
   * The table <code>mydata.login_user_information</code>.
   */
  public static final LoginUserInformation LOGIN_USER_INFORMATION = cn.personal.jooq.model.jooq.tables.LoginUserInformation.LOGIN_USER_INFORMATION;

  /**
   * The table <code>mydata.module</code>.
   */
  public static final Module MODULE = cn.personal.jooq.model.jooq.tables.Module.MODULE;

  /**
   * The table <code>mydata.module_role</code>.
   */
  public static final ModuleRole MODULE_ROLE = cn.personal.jooq.model.jooq.tables.ModuleRole.MODULE_ROLE;

  /**
   * The table <code>mydata.mycat_seqlg</code>.
   */
  public static final MycatSeqlg MYCAT_SEQLG = cn.personal.jooq.model.jooq.tables.MycatSeqlg.MYCAT_SEQLG;

  /**
   * 操作日志表
   */
  public static final OperationLog OPERATION_LOG = cn.personal.jooq.model.jooq.tables.OperationLog.OPERATION_LOG;

  /**
   * The table <code>mydata.portal_resource</code>.
   */
  public static final PortalResource PORTAL_RESOURCE = cn.personal.jooq.model.jooq.tables.PortalResource.PORTAL_RESOURCE;

  /**
   * The table <code>mydata.product</code>.
   */
  public static final Product PRODUCT = cn.personal.jooq.model.jooq.tables.Product.PRODUCT;

  /**
   * The table <code>mydata.p_user</code>.
   */
  public static final PUser P_USER = cn.personal.jooq.model.jooq.tables.PUser.P_USER;

  /**
   * The table <code>mydata.role</code>.
   */
  public static final Role ROLE = cn.personal.jooq.model.jooq.tables.Role.ROLE;

  /**
   * The table <code>mydata.user_role</code>.
   */
  public static final UserRole USER_ROLE = cn.personal.jooq.model.jooq.tables.UserRole.USER_ROLE;
}
