/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import javax.annotation.Generated;


/**
 * 用户资产表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LgUserAmount implements Serializable {

  private static final long serialVersionUID = -1578447026;

  private Long id;
  private Long companyUserId;
  private BigDecimal amount;
  private String amountType;
  private LocalDateTime createTime;
  private Long createId;
  private LocalDateTime updateTime;
  private Long updateId;
  private String deleteFlag;

  public LgUserAmount() {
  }

  public LgUserAmount(LgUserAmount value) {
    this.id = value.id;
    this.companyUserId = value.companyUserId;
    this.amount = value.amount;
    this.amountType = value.amountType;
    this.createTime = value.createTime;
    this.createId = value.createId;
    this.updateTime = value.updateTime;
    this.updateId = value.updateId;
    this.deleteFlag = value.deleteFlag;
  }

  public LgUserAmount(
      Long id,
      Long companyUserId,
      BigDecimal amount,
      String amountType,
      LocalDateTime createTime,
      Long createId,
      LocalDateTime updateTime,
      Long updateId,
      String deleteFlag
  ) {
    this.id = id;
    this.companyUserId = companyUserId;
    this.amount = amount;
    this.amountType = amountType;
    this.createTime = createTime;
    this.createId = createId;
    this.updateTime = updateTime;
    this.updateId = updateId;
    this.deleteFlag = deleteFlag;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Long getCompanyUserId() {
    return this.companyUserId;
  }

  public void setCompanyUserId(Long companyUserId) {
    this.companyUserId = companyUserId;
  }

  public BigDecimal getAmount() {
    return this.amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public String getAmountType() {
    return this.amountType;
  }

  public void setAmountType(String amountType) {
    this.amountType = amountType;
  }

  public LocalDateTime getCreateTime() {
    return this.createTime;
  }

  public void setCreateTime(LocalDateTime createTime) {
    this.createTime = createTime;
  }

  public Long getCreateId() {
    return this.createId;
  }

  public void setCreateId(Long createId) {
    this.createId = createId;
  }

  public LocalDateTime getUpdateTime() {
    return this.updateTime;
  }

  public void setUpdateTime(LocalDateTime updateTime) {
    this.updateTime = updateTime;
  }

  public Long getUpdateId() {
    return this.updateId;
  }

  public void setUpdateId(Long updateId) {
    this.updateId = updateId;
  }

  public String getDeleteFlag() {
    return this.deleteFlag;
  }

  public void setDeleteFlag(String deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LgUserAmount (");

    sb.append(id);
    sb.append(", ").append(companyUserId);
    sb.append(", ").append(amount);
    sb.append(", ").append(amountType);
    sb.append(", ").append(createTime);
    sb.append(", ").append(createId);
    sb.append(", ").append(updateTime);
    sb.append(", ").append(updateId);
    sb.append(", ").append(deleteFlag);

    sb.append(")");
    return sb.toString();
  }
}
