/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.pojos;


import java.io.Serializable;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LoginUserInformation implements Serializable {

  private static final long serialVersionUID = -1407015957;

  private Integer id;
  private Long userId;
  private String account;
  private String password;

  public LoginUserInformation() {
  }

  public LoginUserInformation(LoginUserInformation value) {
    this.id = value.id;
    this.userId = value.userId;
    this.account = value.account;
    this.password = value.password;
  }

  public LoginUserInformation(
      Integer id,
      Long userId,
      String account,
      String password
  ) {
    this.id = id;
    this.userId = userId;
    this.account = account;
    this.password = password;
  }

  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Long getUserId() {
    return this.userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public String getAccount() {
    return this.account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LoginUserInformation (");

    sb.append(id);
    sb.append(", ").append(userId);
    sb.append(", ").append(account);
    sb.append(", ").append(password);

    sb.append(")");
    return sb.toString();
  }
}
