/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.pojos;


import java.io.Serializable;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ModuleRole implements Serializable {

  private static final long serialVersionUID = 1208296315;

  private Integer rid;
  private Integer mid;

  public ModuleRole() {
  }

  public ModuleRole(ModuleRole value) {
    this.rid = value.rid;
    this.mid = value.mid;
  }

  public ModuleRole(
      Integer rid,
      Integer mid
  ) {
    this.rid = rid;
    this.mid = mid;
  }

  public Integer getRid() {
    return this.rid;
  }

  public void setRid(Integer rid) {
    this.rid = rid;
  }

  public Integer getMid() {
    return this.mid;
  }

  public void setMid(Integer mid) {
    this.mid = mid;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ModuleRole (");

    sb.append(rid);
    sb.append(", ").append(mid);

    sb.append(")");
    return sb.toString();
  }
}
