/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.pojos;


import java.io.Serializable;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Module implements Serializable {

  private static final long serialVersionUID = -1204621852;

  private Integer mid;
  private Integer parentId;
  private String mname;
  private String moduleType;
  private String isDefault;
  private String status;
  private String menuUrl;
  private Short showPosition;

  public Module() {
  }

  public Module(Module value) {
    this.mid = value.mid;
    this.parentId = value.parentId;
    this.mname = value.mname;
    this.moduleType = value.moduleType;
    this.isDefault = value.isDefault;
    this.status = value.status;
    this.menuUrl = value.menuUrl;
    this.showPosition = value.showPosition;
  }

  public Module(
      Integer mid,
      Integer parentId,
      String mname,
      String moduleType,
      String isDefault,
      String status,
      String menuUrl,
      Short showPosition
  ) {
    this.mid = mid;
    this.parentId = parentId;
    this.mname = mname;
    this.moduleType = moduleType;
    this.isDefault = isDefault;
    this.status = status;
    this.menuUrl = menuUrl;
    this.showPosition = showPosition;
  }

  public Integer getMid() {
    return this.mid;
  }

  public void setMid(Integer mid) {
    this.mid = mid;
  }

  public Integer getParentId() {
    return this.parentId;
  }

  public void setParentId(Integer parentId) {
    this.parentId = parentId;
  }

  public String getMname() {
    return this.mname;
  }

  public void setMname(String mname) {
    this.mname = mname;
  }

  public String getModuleType() {
    return this.moduleType;
  }

  public void setModuleType(String moduleType) {
    this.moduleType = moduleType;
  }

  public String getIsDefault() {
    return this.isDefault;
  }

  public void setIsDefault(String isDefault) {
    this.isDefault = isDefault;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getMenuUrl() {
    return this.menuUrl;
  }

  public void setMenuUrl(String menuUrl) {
    this.menuUrl = menuUrl;
  }

  public Short getShowPosition() {
    return this.showPosition;
  }

  public void setShowPosition(Short showPosition) {
    this.showPosition = showPosition;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Module (");

    sb.append(mid);
    sb.append(", ").append(parentId);
    sb.append(", ").append(mname);
    sb.append(", ").append(moduleType);
    sb.append(", ").append(isDefault);
    sb.append(", ").append(status);
    sb.append(", ").append(menuUrl);
    sb.append(", ").append(showPosition);

    sb.append(")");
    return sb.toString();
  }
}
