/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.pojos;


import java.io.Serializable;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MycatSeqlg implements Serializable {

  private static final long serialVersionUID = -1490440720;

  private String name;
  private Integer currentValue;
  private Integer increment;

  public MycatSeqlg() {
  }

  public MycatSeqlg(MycatSeqlg value) {
    this.name = value.name;
    this.currentValue = value.currentValue;
    this.increment = value.increment;
  }

  public MycatSeqlg(
      String name,
      Integer currentValue,
      Integer increment
  ) {
    this.name = name;
    this.currentValue = currentValue;
    this.increment = increment;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Integer getCurrentValue() {
    return this.currentValue;
  }

  public void setCurrentValue(Integer currentValue) {
    this.currentValue = currentValue;
  }

  public Integer getIncrement() {
    return this.increment;
  }

  public void setIncrement(Integer increment) {
    this.increment = increment;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MycatSeqlg (");

    sb.append(name);
    sb.append(", ").append(currentValue);
    sb.append(", ").append(increment);

    sb.append(")");
    return sb.toString();
  }
}
