/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PortalResource implements Serializable {

  private static final long serialVersionUID = 1680143062;

  private Long id;
  private Long shelfUserId;
  private String shelfUserName;
  private String portalName;
  private LocalDateTime createTime;

  public PortalResource() {
  }

  public PortalResource(PortalResource value) {
    this.id = value.id;
    this.shelfUserId = value.shelfUserId;
    this.shelfUserName = value.shelfUserName;
    this.portalName = value.portalName;
    this.createTime = value.createTime;
  }

  public PortalResource(
      Long id,
      Long shelfUserId,
      String shelfUserName,
      String portalName,
      LocalDateTime createTime
  ) {
    this.id = id;
    this.shelfUserId = shelfUserId;
    this.shelfUserName = shelfUserName;
    this.portalName = portalName;
    this.createTime = createTime;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Long getShelfUserId() {
    return this.shelfUserId;
  }

  public void setShelfUserId(Long shelfUserId) {
    this.shelfUserId = shelfUserId;
  }

  public String getShelfUserName() {
    return this.shelfUserName;
  }

  public void setShelfUserName(String shelfUserName) {
    this.shelfUserName = shelfUserName;
  }

  public String getPortalName() {
    return this.portalName;
  }

  public void setPortalName(String portalName) {
    this.portalName = portalName;
  }

  public LocalDateTime getCreateTime() {
    return this.createTime;
  }

  public void setCreateTime(LocalDateTime createTime) {
    this.createTime = createTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PortalResource (");

    sb.append(id);
    sb.append(", ").append(shelfUserId);
    sb.append(", ").append(shelfUserName);
    sb.append(", ").append(portalName);
    sb.append(", ").append(createTime);

    sb.append(")");
    return sb.toString();
  }
}
