/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.pojos;


import java.io.Serializable;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Product implements Serializable {

  private static final long serialVersionUID = 391605670;

  private Long id;
  private String productname;
  private String productcontent;
  private String price;
  private Integer sort;

  public Product() {
  }

  public Product(Product value) {
    this.id = value.id;
    this.productname = value.productname;
    this.productcontent = value.productcontent;
    this.price = value.price;
    this.sort = value.sort;
  }

  public Product(
      Long id,
      String productname,
      String productcontent,
      String price,
      Integer sort
  ) {
    this.id = id;
    this.productname = productname;
    this.productcontent = productcontent;
    this.price = price;
    this.sort = sort;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getProductname() {
    return this.productname;
  }

  public void setProductname(String productname) {
    this.productname = productname;
  }

  public String getProductcontent() {
    return this.productcontent;
  }

  public void setProductcontent(String productcontent) {
    this.productcontent = productcontent;
  }

  public String getPrice() {
    return this.price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public Integer getSort() {
    return this.sort;
  }

  public void setSort(Integer sort) {
    this.sort = sort;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Product (");

    sb.append(id);
    sb.append(", ").append(productname);
    sb.append(", ").append(productcontent);
    sb.append(", ").append(price);
    sb.append(", ").append(sort);

    sb.append(")");
    return sb.toString();
  }
}
