/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables.pojos;


import java.io.Serializable;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PUser implements Serializable {

  private static final long serialVersionUID = 226894050;

  private Integer uid;
  private String username;
  private String password;
  private String uname;
  private Integer age;
  private String sex;
  private String address;
  private Integer version;

  public PUser() {
  }

  public PUser(PUser value) {
    this.uid = value.uid;
    this.username = value.username;
    this.password = value.password;
    this.uname = value.uname;
    this.age = value.age;
    this.sex = value.sex;
    this.address = value.address;
    this.version = value.version;
  }

  public PUser(
      Integer uid,
      String username,
      String password,
      String uname,
      Integer age,
      String sex,
      String address,
      Integer version
  ) {
    this.uid = uid;
    this.username = username;
    this.password = password;
    this.uname = uname;
    this.age = age;
    this.sex = sex;
    this.address = address;
    this.version = version;
  }

  public Integer getUid() {
    return this.uid;
  }

  public void setUid(Integer uid) {
    this.uid = uid;
  }

  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getUname() {
    return this.uname;
  }

  public void setUname(String uname) {
    this.uname = uname;
  }

  public Integer getAge() {
    return this.age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  public String getSex() {
    return this.sex;
  }

  public void setSex(String sex) {
    this.sex = sex;
  }

  public String getAddress() {
    return this.address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public Integer getVersion() {
    return this.version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PUser (");

    sb.append(uid);
    sb.append(", ").append(username);
    sb.append(", ").append(password);
    sb.append(", ").append(uname);
    sb.append(", ").append(age);
    sb.append(", ").append(sex);
    sb.append(", ").append(address);
    sb.append(", ").append(version);

    sb.append(")");
    return sb.toString();
  }
}
