/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.routines;


import cn.personal.jooq.model.jooq.Mydata;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MycatSeqNextval extends AbstractRoutine<String> {

  private static final long serialVersionUID = 1684235096;

  /**
   * The parameter <code>mydata.mycat_seq_nextval.RETURN_VALUE</code>.
   */
  public static final Parameter<String> RETURN_VALUE = Internal
      .createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR(64), false, false);

  /**
   * The parameter <code>mydata.mycat_seq_nextval.seq_name</code>.
   */
  public static final Parameter<String> SEQ_NAME = Internal
      .createParameter("seq_name", org.jooq.impl.SQLDataType.VARCHAR(50), false, false);

  /**
   * Create a new routine call instance
   */
  public MycatSeqNextval() {
    super("mycat_seq_nextval", Mydata.MYDATA, org.jooq.impl.SQLDataType.VARCHAR(64));

    setReturnParameter(RETURN_VALUE);
    addInParameter(SEQ_NAME);
  }

  /**
   * Set the <code>seq_name</code> parameter IN value to the routine
   */
  public void setSeqName(String value) {
    setValue(SEQ_NAME, value);
  }

  /**
   * Set the <code>seq_name</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setSeqName(Field<String> field) {
    setField(SEQ_NAME, field);
  }
}
