/*
 * This file is generated by jOOQ.
 */
package cn.personal.jooq.model.jooq.tables;


import cn.personal.jooq.model.jooq.Indexes;
import cn.personal.jooq.model.jooq.Keys;
import cn.personal.jooq.model.jooq.Mydata;
import cn.personal.jooq.model.jooq.tables.records.ModuleRoleRecord;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ModuleRole extends TableImpl<ModuleRoleRecord> {

  private static final long serialVersionUID = -2105884292;

  /**
   * The reference instance of <code>mydata.module_role</code>
   */
  public static final ModuleRole MODULE_ROLE = new ModuleRole();

  /**
   * The class holding records for this type
   */
  @Override
  public Class<ModuleRoleRecord> getRecordType() {
    return ModuleRoleRecord.class;
  }

  /**
   * The column <code>mydata.module_role.rid</code>.
   */
  public final TableField<ModuleRoleRecord, Integer> RID = createField("rid",
      org.jooq.impl.SQLDataType.INTEGER, this, "");

  /**
   * The column <code>mydata.module_role.mid</code>.
   */
  public final TableField<ModuleRoleRecord, Integer> MID = createField("mid",
      org.jooq.impl.SQLDataType.INTEGER, this, "");

  /**
   * Create a <code>mydata.module_role</code> table reference
   */
  public ModuleRole() {
    this(DSL.name("module_role"), null);
  }

  /**
   * Create an aliased <code>mydata.module_role</code> table reference
   */
  public ModuleRole(String alias) {
    this(DSL.name(alias), MODULE_ROLE);
  }

  /**
   * Create an aliased <code>mydata.module_role</code> table reference
   */
  public ModuleRole(Name alias) {
    this(alias, MODULE_ROLE);
  }

  private ModuleRole(Name alias, Table<ModuleRoleRecord> aliased) {
    this(alias, aliased, null);
  }

  private ModuleRole(Name alias, Table<ModuleRoleRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""));
  }

  public <O extends Record> ModuleRole(Table<O> child, ForeignKey<O, ModuleRoleRecord> key) {
    super(child, key, MODULE_ROLE);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Schema getSchema() {
    return Mydata.MYDATA;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public List<Index> getIndexes() {
    return Arrays.<Index>asList(Indexes.MODULE_ROLE_MID, Indexes.MODULE_ROLE_RID);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public List<ForeignKey<ModuleRoleRecord, ?>> getReferences() {
    return Arrays.<ForeignKey<ModuleRoleRecord, ?>>asList(Keys.RID, Keys.MID);
  }

  public Role role() {
    return new Role(this, Keys.RID);
  }

  public Module module() {
    return new Module(this, Keys.MID);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRole as(String alias) {
    return new ModuleRole(DSL.name(alias), this);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ModuleRole as(Name alias) {
    return new ModuleRole(alias, this);
  }

  /**
   * Rename this table
   */
  @Override
  public ModuleRole rename(String name) {
    return new ModuleRole(DSL.name(name), null);
  }

  /**
   * Rename this table
   */
  @Override
  public ModuleRole rename(Name name) {
    return new ModuleRole(name, null);
  }
}
